name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Remove PR trigger for production deployment
  # pull_request:
  #   branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Production deployment workflow - tests are handled by lefthook pre-push in development
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production
          VITE_FMP_BASE_URL: "https://financialmodelingprep.com/api/v3"
          VITE_FMP_API_KEY: ${{ secrets.VITE_FMP_API_KEY }}

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
